export const list = [
  {
    title: "TM Agency Banking",
    desc: "It's the ultimate solution designed to deliver efficiency, security, and seamlessness to your agency banking experience.",
    link: "https://agencybanking.tm30.net/",
    src: "/gifs/tmagency.gif",
    type: "REACT/VITE",
  },
  /*   {
    title: "Hope Payment Service Bank",
    desc: "It's the ultimate solution designed to deliver efficiency, security, and seamlessness to your agency banking experience.",
    link: "https://agencybanking.tm30.net/",
    src: tmagency,
    type: "REACT/VITE",
  }, */
  {
    title: "Takeout Media",
    desc: "Takeout is a Design Agency. At Dork we helped them build an online presence with captivating visuals",
    link: "https://takeoutmedia.xyz/",
    src: "/gifs/takeout.gif",
    type: "VUE",
  },
  {
    title: "Recital Finance",
    desc: "Supercharged Payment and Financial Operations Infrastructure for Growing Businesses. It's and Enterprise Financial Operations & Liquidity Management platform",
    link: "https://recital.finance/",
    src: "/gifs/recital.gif",
    type: "REACT/NEXT",
    side: true,
  },
  {
    title: "Digitslaw",
    desc: "It's a All-in-one law practice software. Easiest, intuitive and most organized way to manage your law firm, clients, cases, billing, accounting and more.",
    link: "https://digitslaw.com/",
    src: "/gifs/digitslaw.gif",
    type: "REACT/NEXT",
  },
  {
    title: "Propkip",
    desc: "This is a service provision software, get your quick service easily e.g laundry, plumbing etc.",
    src: "/gifs/propkip.gif",
    link: "https://www.propkip.com/",
    type: "VUE",
  },
  {
    title: "Nasida (NASARAWA INVESTMENT AND DEVELOPMENT AGENCY) Website",
    desc: "NASIDA is the Nasarawa Investment and Development Agency, created through an act of the Nasarawa State House of Assembly to initiate, promote, facilitate and coordinate investments in Nasarawa State, whether it be public private partnerships, privatization, concessions or commercialization of state owned assets.",
    src: "/gifs/nasida.gif",
    link: "https://nasida.na.gov.ng/",
    type: "VUE",
  },
  {
    title: "Paymybills",
    desc: "Paymybills helps you to add and manage all your bills in one place. View a list of all your upcoming bills and their due dates..",
    src: "/gifs/paymybills.gif",
    link: "https://www.paymybills.ng/",
    type: "REACT",
  },
  {
    title: "Coventi",
    desc: "Coventi is an on demand Video Streaming platform for Events for the Culture and Movies. It is a platform that allows you to watch live events and also watch replays of past events.",
    src: "/gifs/coventi.gif",
    link: "https://coventi.co/",
    type: "VUE",
    side: true,
  },
  {
    title: "Transfer Rocket",
    desc: "Transfer rocket is an inter country money transfer platform, mostly aids the transfer of funds from Nigeria to the UK, as well as US and few countries in europe. This platform is best  experienced on mobile.",
    src: "/gifs/rocket.gif",
    link: "https://dashboard.transferrocket.co.uk/",
    type: "REACT",
    side: true,
  },
  {
    title: "Fyrre",
    desc: "Fyrre is a simple and visually appealing art magazine site",
    src: "/gifs/fyrre.gif",
    link: "https://fyrre.vercel.app/",
    side: true,
  },
  {
    title: "Vue Nav UI",
    desc: "This is a custom navbar vuejs package that I developed. This was built on vue js 3 and the new composition api",
    src: "/gifs/nav-ui.gif",
    link: "https://dhanielcodes.github.io/vue-navigation-ui/",
    type: "VUE",
    side: true,
  },
];
